apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "metallb.fullname" . }}-ip-address-pool-configmap  
  namespace: {{ .Release.Namespace | quote }}

data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - {{ .Values.ipAddressPool.addressRange }}