apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.ipAddressPool.namespace }}
  name: {{ .Values.ipAddressPool.name }}
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - {{ .Values.ipAddressPool.addressRange }}

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - {{ .Values.ipAddressPool.addressRange }}
      