apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.ipAddressPool.namespace }}
  name: {{ .Values.ipAddressPool.name }}
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - {{ .Values.ipAddressPool.addressRange }}
