apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.ipAddressPool.name }}
  namespace: {{ .Values.ipAddressPool.namespace }}
spec:
  addresses:
  - {{ .Values.ipAddressPool.addressRange }}
